export type ActivityActionType =
  | "task_created"
  | "task_completed"
  | "task_moved"
  | "task_updated"
  | "task_deleted"
  | "meeting_started"
  | "meeting_ended"
  | "meeting_recorded"
  | "file_uploaded"
  | "client_at_risk"
  | "client_lifecycle_changed"
  | "team_invited"
  | "team_invite_resent"
  | "team_role_changed"
  | "team_access_activated"
  | "team_access_deactivated";
