-- Distributed Gemini quotas and metadata-only observability.
-- Both tables are server-only: browser roles receive no privileges or policies.

create table if not exists public.ai_usage_buckets (
  user_id uuid not null references auth.users(id) on delete cascade,
  route text not null check (length(route) between 1 and 120),
  window_kind text not null check (window_kind in ('hour', 'day')),
  window_start timestamptz not null,
  request_count bigint not null default 0 check (request_count >= 0),
  input_chars bigint not null default 0 check (input_chars >= 0),
  updated_at timestamptz not null default now(),
  primary key (user_id, route, window_kind, window_start)
);

create index if not exists ai_usage_buckets_window_idx on public.ai_usage_buckets (window_kind, window_start);
alter table public.ai_usage_buckets enable row level security;
alter table public.ai_usage_buckets force row level security;
revoke all on table public.ai_usage_buckets from public, anon, authenticated;
grant select, insert, update, delete on table public.ai_usage_buckets to service_role;

create table if not exists public.ai_request_log (
  id bigint generated by default as identity primary key,
  request_id text not null unique check (length(request_id) between 1 and 128),
  user_id uuid references auth.users(id) on delete set null,
  route text not null check (length(route) between 1 and 120),
  input_chars integer not null check (input_chars >= 0),
  duration_ms integer not null check (duration_ms >= 0),
  status_code integer not null check (status_code between 100 and 599),
  outcome text not null check (length(outcome) between 1 and 80),
  created_at timestamptz not null default now()
);

create index if not exists ai_request_log_user_created_idx on public.ai_request_log (user_id, created_at desc);
create index if not exists ai_request_log_route_created_idx on public.ai_request_log (route, created_at desc);
alter table public.ai_request_log enable row level security;
alter table public.ai_request_log force row level security;
revoke all on table public.ai_request_log from public, anon, authenticated;
grant select, insert on table public.ai_request_log to service_role;
grant usage, select on sequence public.ai_request_log_id_seq to service_role;

create or replace function public.reserve_ai_quota(
  p_user_id uuid,
  p_route text,
  p_input_chars integer,
  p_hourly_limit integer default 20,
  p_daily_char_limit integer default 500000
)
returns table (
  allowed boolean,
  retry_after_seconds integer,
  hourly_count bigint,
  daily_chars bigint
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  normalized_route text := trim(p_route);
  current_time timestamptz := clock_timestamp();
  hour_start timestamptz := date_trunc('hour', current_time);
  day_start timestamptz := date_trunc('day', current_time);
  hour_requests bigint;
  day_characters bigint;
  wait_seconds integer := 0;
begin
  if p_user_id is null
     or normalized_route = ''
     or length(normalized_route) > 120
     or p_input_chars < 0
     or p_hourly_limit <= 0
     or p_daily_char_limit <= 0 then
    raise exception 'Invalid AI quota reservation.' using errcode = '22023';
  end if;

  insert into public.ai_usage_buckets (user_id, route, window_kind, window_start)
  values
    (p_user_id, normalized_route, 'hour', hour_start),
    (p_user_id, normalized_route, 'day', day_start)
  on conflict do nothing;

  perform 1
  from public.ai_usage_buckets
  where user_id = p_user_id
    and route = normalized_route
    and (
      (window_kind = 'hour' and window_start = hour_start)
      or (window_kind = 'day' and window_start = day_start)
    )
  order by window_kind
  for update;

  select request_count into hour_requests
  from public.ai_usage_buckets
  where user_id = p_user_id and route = normalized_route and window_kind = 'hour' and window_start = hour_start;

  select input_chars into day_characters
  from public.ai_usage_buckets
  where user_id = p_user_id and route = normalized_route and window_kind = 'day' and window_start = day_start;

  if hour_requests + 1 > p_hourly_limit then
    wait_seconds := greatest(wait_seconds, ceil(extract(epoch from (hour_start + interval '1 hour' - current_time)))::integer + 1);
  end if;
  if day_characters + p_input_chars > p_daily_char_limit then
    wait_seconds := greatest(wait_seconds, ceil(extract(epoch from (day_start + interval '1 day' - current_time)))::integer + 1);
  end if;

  if wait_seconds > 0 then
    return query select false, wait_seconds, hour_requests, day_characters;
    return;
  end if;

  update public.ai_usage_buckets
  set request_count = request_count + 1, input_chars = input_chars + p_input_chars, updated_at = current_time
  where user_id = p_user_id and route = normalized_route and window_kind = 'hour' and window_start = hour_start;

  update public.ai_usage_buckets
  set request_count = request_count + 1, input_chars = input_chars + p_input_chars, updated_at = current_time
  where user_id = p_user_id and route = normalized_route and window_kind = 'day' and window_start = day_start;

  return query select true, 0, hour_requests + 1, day_characters + p_input_chars;
end;
$$;

revoke all on function public.reserve_ai_quota(uuid, text, integer, integer, integer) from public, anon, authenticated;
grant execute on function public.reserve_ai_quota(uuid, text, integer, integer, integer) to service_role;

comment on table public.ai_usage_buckets is 'Server-only hourly request and daily input-character budgets for Gemini routes.';
comment on table public.ai_request_log is 'Metadata-only AI request audit; never stores prompts, documents, notes, transcripts, or model responses.';
comment on function public.reserve_ai_quota(uuid, text, integer, integer, integer) is 'Service-role-only atomic reservation for per-user, per-route Gemini quotas.';
